#############################################################################
# Generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#  Feb 01, 2021 02:35:55 PM CET  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 677x551+335+236
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3460 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "DatasetTool"
    vTcl:DefineAlias "$top" "Toplevel" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list disabled $vTcl(actual_gui_bg) selected $vTcl(complement_color)]
    ttk::notebook $top.tNo45 \
        -width 604 -height 456 -takefocus {} 
    vTcl:DefineAlias "$top.tNo45" "TNotebookMenu" vTcl:WidgetProc "Toplevel" 1
    frame $top.tNo45.t0 \
        -background #caffca -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo45.t0" "TNotebookMenu_t1" vTcl:WidgetProc "Toplevel" 1
    $top.tNo45 add $top.tNo45.t0 \
        -padding 5 -sticky nsew -state normal -text ImageCombiner -image {} \
        -compound left -underline -1 
    set site_4_0  $top.tNo45.t0
    ttk::label $site_4_0.tLa47 \
        -background #b1e2fc -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -textvariable chosen_directory 
    vTcl:DefineAlias "$site_4_0.tLa47" "TLabelChosenDir" vTcl:WidgetProc "Toplevel" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_4_0.tBu48 \
        -command change_dir -takefocus {} \
        -text {Change ImageCombiner Directory} 
    vTcl:DefineAlias "$site_4_0.tBu48" "TButtonChangeDir" vTcl:WidgetProc "Toplevel" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_4_0.tBu49 \
        -command image_combiner -takefocus {} -text {Run ImageCombiner} 
    vTcl:DefineAlias "$site_4_0.tBu49" "TButtonImageCombiner" vTcl:WidgetProc "Toplevel" 1
    message $site_4_0.mes50 \
        -background #caffca -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {ImageCombiner creates 48 smaller pictures from the original 6.
If you chose directory with only 6 images inside it will combine only those 6.
If you chose a directory with subdirectories it will iterate through all of them and combine them in each one.
Some images may be taken in reverse order, check the ReverseSort option before running ImageCombiner.} \
        -width 571 
    vTcl:DefineAlias "$site_4_0.mes50" "MessageHowToImageCombiner" vTcl:WidgetProc "Toplevel" 1
    checkbutton $site_4_0.che51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command set_reverse_sort \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text ReverseSort -variable che51 
    vTcl:DefineAlias "$site_4_0.che51" "CheckReverseSort" vTcl:WidgetProc "Toplevel" 1
    message $site_4_0.mes45 \
        -anchor w -background #caffca -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Status: -textvariable image_combiner_status -width 290 
    vTcl:DefineAlias "$site_4_0.mes45" "Message2" vTcl:WidgetProc "Toplevel" 1
    place $site_4_0.tLa47 \
        -in $site_4_0 -x 0 -relx 0.09 -y 0 -rely 0.364 -width 0 \
        -relwidth 0.861 -height 0 -relheight 0.094 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tBu48 \
        -in $site_4_0 -x 0 -relx 0.659 -y 0 -rely 0.498 -width 196 \
        -relwidth 0 -height 45 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tBu49 \
        -in $site_4_0 -x 0 -relx 0.09 -y 0 -rely 0.805 -width 156 -relwidth 0 \
        -height 55 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.mes50 \
        -in $site_4_0 -x 0 -relx 0.09 -y 0 -rely 0.057 -width 0 \
        -relwidth 0.855 -height 0 -relheight 0.216 -anchor nw \
        -bordermode ignore 
    place $site_4_0.che51 \
        -in $site_4_0 -x 0 -relx 0.09 -y 0 -rely 0.69 -width 0 \
        -relwidth 0.151 -height 0 -relheight 0.048 -anchor nw \
        -bordermode ignore 
    place $site_4_0.mes45 \
        -in $site_4_0 -x 0 -relx 0.359 -y 0 -rely 0.805 -width 0 \
        -relwidth 0.434 -height 0 -relheight 0.102 -anchor nw \
        -bordermode ignore 
    frame $top.tNo45.t1 \
        -background #caffca -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo45.t1" "TNotebookMenu_t2" vTcl:WidgetProc "Toplevel" 1
    $top.tNo45 add $top.tNo45.t1 \
        -padding 5 -sticky nsew -state normal -text AutoLabel -image {} \
        -compound left -underline -1 
    set site_4_1  $top.tNo45.t1
    ttk::style configure TRadiobutton -background $vTcl(actual_gui_bg)
    ttk::style configure TRadiobutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TRadiobutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::radiobutton $site_4_1.tRa54 \
        -value 0 -command set_sample_type -text {Dry Sample} 
    vTcl:DefineAlias "$site_4_1.tRa54" "TRadioDrySample" vTcl:WidgetProc "Toplevel" 1
    ttk::style configure TRadiobutton -background $vTcl(actual_gui_bg)
    ttk::style configure TRadiobutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TRadiobutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::radiobutton $site_4_1.tRa55 \
        -command set_sample_type -text {Oil Sample} 
    vTcl:DefineAlias "$site_4_1.tRa55" "TRadioOilSample" vTcl:WidgetProc "Toplevel" 1
    ttk::label $site_4_1.tLa45 \
        -background #b1e2fc -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -textvariable chosen_label_dir 
    vTcl:DefineAlias "$site_4_1.tLa45" "TLabelDirLabel" vTcl:WidgetProc "Toplevel" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_4_1.tBu46 \
        -command change_label_dir -takefocus {} \
        -text {Change Label Directory} 
    vTcl:DefineAlias "$site_4_1.tBu46" "TButtonChangeLabelDir" vTcl:WidgetProc "Toplevel" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_4_1.tBu47 \
        -command auto_label -takefocus {} -text {Start AutoLabel} 
    vTcl:DefineAlias "$site_4_1.tBu47" "TButtonAutoLabel" vTcl:WidgetProc "Toplevel" 1
    message $site_4_1.mes48 \
        -background #caffca -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {AutoLabeling tries to automatically label pelods on the image and creates xml file.
If you chose directory with only images inside it will label them.
If you chose a directory with subdirectories it will iterate through all of them and label them in each one.
Write pelod name and chose the type of the collected pelod before starting AutoLabel} \
        -width 570 
    vTcl:DefineAlias "$site_4_1.mes48" "Message1" vTcl:WidgetProc "Toplevel" 1
    ttk::entry $site_4_1.tEn45 \
        -font TkTextFont -textvariable pelod_name -foreground {} \
        -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$site_4_1.tEn45" "TEntryPelodName" vTcl:WidgetProc "Toplevel" 1
    bind $site_4_1.tEn45 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Enter pelod name:}
    }
    ttk::label $site_4_1.tLa46 \
        -background #caffca -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text {Write pelod name:} 
    vTcl:DefineAlias "$site_4_1.tLa46" "TLabelPelodEntry" vTcl:WidgetProc "Toplevel" 1
    message $site_4_1.mes46 \
        -anchor w -background #caffca -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -textvariable auto_label_status -width 330 
    vTcl:DefineAlias "$site_4_1.mes46" "Message3" vTcl:WidgetProc "Toplevel" 1
    place $site_4_1.tRa54 \
        -in $site_4_1 -x 0 -relx 0.105 -y 0 -rely 0.651 -width 0 \
        -relwidth 0.253 -height 0 -relheight 0.04 -anchor nw \
        -bordermode ignore 
    place $site_4_1.tRa55 \
        -in $site_4_1 -x 0 -relx 0.105 -y 0 -rely 0.69 -width 0 \
        -relwidth 0.253 -height 0 -relheight 0.04 -anchor nw \
        -bordermode ignore 
    place $site_4_1.tLa45 \
        -in $site_4_1 -x 0 -relx 0.09 -y 0 -rely 0.268 -width 0 \
        -relwidth 0.853 -height 0 -relheight 0.094 -anchor nw \
        -bordermode ignore 
    place $site_4_1.tBu46 \
        -in $site_4_1 -x 0 -relx 0.674 -y 0 -rely 0.421 -width 186 \
        -relwidth 0 -height 45 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.tBu47 \
        -in $site_4_1 -x 0 -relx 0.105 -y 0 -rely 0.805 -width 176 \
        -relwidth 0 -height 55 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.mes48 \
        -in $site_4_1 -x 0 -relx 0.09 -y 0 -rely 0.038 -width 0 \
        -relwidth 0.853 -height 0 -relheight 0.178 -anchor nw \
        -bordermode ignore 
    place $site_4_1.tEn45 \
        -in $site_4_1 -x 0 -relx 0.105 -y 0 -rely 0.594 -width 0 \
        -relwidth 0.189 -height 0 -relheight 0.04 -anchor nw \
        -bordermode ignore 
    place $site_4_1.tLa46 \
        -in $site_4_1 -x 0 -relx 0.105 -y 0 -rely 0.556 -width 0 \
        -relwidth 0.157 -height 0 -relheight 0.036 -anchor nw \
        -bordermode ignore 
    place $site_4_1.mes46 \
        -in $site_4_1 -x 0 -relx 0.419 -y 0 -rely 0.805 -width 0 \
        -relwidth 0.494 -height 0 -relheight 0.102 -anchor nw \
        -bordermode ignore 
    frame $top.tNo45.t2 \
        -background #caffca -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo45.t2" "TNotebookMenu_t3" vTcl:WidgetProc "Toplevel" 1
    $top.tNo45 add $top.tNo45.t2 \
        -padding 5 -sticky nsew -state normal -text LabelImg -image {} \
        -compound left -underline -1 
    set site_4_2  $top.tNo45.t2
    ttk::label $site_4_2.tLa47 \
        -background #b1e2fc -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -textvariable chosen_label_img_dir 
    vTcl:DefineAlias "$site_4_2.tLa47" "TLabelLabelImgDir" vTcl:WidgetProc "Toplevel" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_4_2.tBu48 \
        -command change_label_img_dir -takefocus {} \
        -text {Change LabelImg Directory} 
    vTcl:DefineAlias "$site_4_2.tBu48" "TButtonChangeLabelImgDir" vTcl:WidgetProc "Toplevel" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_4_2.tBu49 \
        -command run_label_img -takefocus {} -text {Run LabelImg} 
    vTcl:DefineAlias "$site_4_2.tBu49" "TButtonLabelImg" vTcl:WidgetProc "Toplevel" 1
    message $site_4_2.mes46 \
        -background #caffca -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Opening LabelImg does not work.} -width 580 
    vTcl:DefineAlias "$site_4_2.mes46" "Message5" vTcl:WidgetProc "Toplevel" 1
    message $site_4_2.mes47 \
        -background #caffca -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Opening LabelImg does not work at the momment.
To open LabelImg, open command prompt, set directory with cd command and run command: python LabelImg.py} \
        -width 580 
    vTcl:DefineAlias "$site_4_2.mes47" "Message4" vTcl:WidgetProc "Toplevel" 1
    place $site_4_2.tLa47 \
        -in $site_4_2 -x 0 -relx 0.06 -y 0 -rely 0.211 -width 0 \
        -relwidth 0.861 -height 0 -relheight 0.113 -anchor nw \
        -bordermode ignore 
    place $site_4_2.tBu48 \
        -in $site_4_2 -x 0 -relx 0.674 -y 0 -rely 0.364 -width 166 \
        -relwidth 0 -height 45 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tBu49 \
        -in $site_4_2 -x 0 -relx 0.075 -y 0 -rely 0.651 -width 156 \
        -relwidth 0 -height 65 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.mes46 \
        -in $site_4_2 -x 0 -relx -0.135 -y 0 -rely -0.441 -width 0 \
        -relwidth 0.861 -height 0 -relheight 0.102 -anchor nw \
        -bordermode ignore 
    place $site_4_2.mes47 \
        -in $site_4_2 -x 0 -relx 0.06 -y 0 -rely 0.038 -width 0 \
        -relwidth 0.861 -height 0 -relheight 0.14 -anchor nw \
        -bordermode ignore 
    frame $top.tNo45.t3 \
        -background #caffca -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo45.t3" "TNotebookMenu_t4" vTcl:WidgetProc "Toplevel" 1
    $top.tNo45 add $top.tNo45.t3 \
        -padding 5 -sticky nsew -state normal -text RestructureAndZip \
        -image {} -compound left -underline -1 
    set site_4_3  $top.tNo45.t3
    ttk::label $site_4_3.tLa45 \
        -background #b1e2fc -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -textvariable chosen_struct_dir 
    vTcl:DefineAlias "$site_4_3.tLa45" "TLabelStructDir" vTcl:WidgetProc "Toplevel" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_4_3.tBu46 \
        -command change_struct_dir -takefocus {} -text {Change  Directory} 
    vTcl:DefineAlias "$site_4_3.tBu46" "TButtonChangeStructDir" vTcl:WidgetProc "Toplevel" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_4_3.tBu47 \
        -command run_restructure_zip -takefocus {} \
        -text {Run Restructure And Zip} 
    vTcl:DefineAlias "$site_4_3.tBu47" "TButton1" vTcl:WidgetProc "Toplevel" 1
    message $site_4_3.mes48 \
        -background #caffca -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Restructure and Zip, takes images(jpg) and labels(xml) and puts them in a seperated foleders and then zip it.
Chose a directory with subdirectories, it will iterate through all of them and combine them in seperated folders.} \
        -width 580 
    vTcl:DefineAlias "$site_4_3.mes48" "Message6" vTcl:WidgetProc "Toplevel" 1
    message $site_4_3.mes45 \
        -anchor w -background #caffca -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -textvariable resturct_status -width 330 
    vTcl:DefineAlias "$site_4_3.mes45" "Message7" vTcl:WidgetProc "Toplevel" 1
    place $site_4_3.tLa45 \
        -in $site_4_3 -x 0 -relx 0.075 -y 0 -rely 0.307 -width 0 \
        -relwidth 0.861 -height 0 -relheight 0.113 -anchor nw \
        -bordermode ignore 
    place $site_4_3.tBu46 \
        -in $site_4_3 -x 0 -relx 0.689 -y 0 -rely 0.441 -width 166 \
        -relwidth 0 -height 45 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_3.tBu47 \
        -in $site_4_3 -x 0 -relx 0.075 -y 0 -rely 0.728 -width 166 \
        -relwidth 0 -height 55 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_3.mes48 \
        -in $site_4_3 -x 0 -relx 0.075 -y 0 -rely 0.077 -width 0 \
        -relwidth 0.861 -height 0 -relheight 0.14 -anchor nw \
        -bordermode ignore 
    place $site_4_3.mes45 \
        -in $site_4_3 -x 0 -relx 0.389 -y 0 -rely 0.728 -width 0 \
        -relwidth 0.494 -height 0 -relheight 0.121 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo45 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1.007 -height 0 \
        -relheight 1.013 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

